name: Trigger auto deployment for container-app-vtalugzryni4a

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'api/**'
    - '.github/workflows/container-app-vtalugzryni4a-AutoDeployTrigger-9e27b982-9818-49d8-abbd-97d5f1a33341.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPVTALUGZRYNI4A_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPVTALUGZRYNI4A_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPVTALUGZRYNI4A_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/api 
          registryUrl: containerregistrymsxw2mmr3hl6m.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPVTALUGZRYNI4A_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPVTALUGZRYNI4A_REGISTRY_PASSWORD }}
          containerAppName: container-app-vtalugzryni4a
          resourceGroup: testdeploymentstatus
          imageToBuild: containerregistrymsxw2mmr3hl6m.azurecr.io/container-app-vtalugzryni4a:${{ github.sha }}
          dockerfilePath: Dockerfile


